ci(gha): add additional jobs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,7 +8,7 @@ on:
 
  
 env:
-    TF_LOG: INFO
+    #TF_LOG: INFO  #debug only
     TF_INPUT: false
 
 jobs: 
@@ -20,14 +20,12 @@ jobs:
                 shell: bash
                 working-directory: ./terraform/core
         steps:
-            # Checkout the repository to the GitHub Actions runner
             - name: Checkout
               uses: actions/checkout@v3
-            # Install the selected version of Terraform CLI 
             - name: Authenticate to GCP
               uses: 'google-github-actions/auth@v2'
               with:
-                credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' # Replace with the name of your GitHub Actions secret
+                credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
             - name: Setup Terraform
               uses: hashicorp/setup-terraform@v2
               with:
@@ -47,12 +45,71 @@ jobs:
               id: plan
               run: terraform plan
 
-    #terraform-services:
-    #    environment: demogcp
-    #    runs-on: ubuntu-latest
-    #    needs: terraform-core
-    #
-    #terraform-application:
-    #    environment: demogcp
-    #    runs-on: ubuntu-latest
-    #    needs: terraform-services
+    terraform-services:
+        environment: demogcp
+        runs-on: ubuntu-latest
+        needs: terraform-core
+        defaults:
+          run:
+              shell: bash
+              working-directory: ./terraform/services
+        steps:
+          - name: Checkout
+            uses: actions/checkout@v3
+          - name: Authenticate to GCP
+            uses: 'google-github-actions/auth@v2'
+            with:
+              credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
+          - name: Setup Terraform
+            uses: hashicorp/setup-terraform@v2
+            with:
+              terraform_version: "1.7.5"
+
+          - name: Terraform Init
+            id: init
+            run: terraform init 
+
+          - name: Terraform Validate
+            id: validate
+            # Run even if formatting fails
+            if: success() || failure()
+            run: terraform validate
+
+          - name: Terraform Apply
+            id: plan
+            run: terraform plan
+
+    
+    terraform-application:
+        environment: demogcp
+        runs-on: ubuntu-latest
+        needs: terraform-services
+        defaults:
+          run:
+              shell: bash
+              working-directory: ./terraform/application
+        steps:
+          - name: Checkout
+            uses: actions/checkout@v3
+          - name: Authenticate to GCP
+            uses: 'google-github-actions/auth@v2'
+            with:
+              credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
+          - name: Setup Terraform
+            uses: hashicorp/setup-terraform@v2
+            with:
+              terraform_version: "1.7.5"
+
+          - name: Terraform Init
+            id: init
+            run: terraform init 
+
+          - name: Terraform Validate
+            id: validate
+            # Run even if formatting fails
+            if: success() || failure()
+            run: terraform validate
+
+          - name: Terraform Apply
+            id: plan
+            run: terraform plan
